id: IF3455C36
ocr_import_info:
  timestamp: '2023-06-16T15:36:23.664569+00:00'
  batch_id: batch-e42f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: pechejob
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-16 15:45:32.722639+00:00
last_modified: 2023-06-16 15:45:32.722647+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W6486
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW6486
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚོགས་དྲུག་རང་གྲོལ་གྱི་རྣམ་ཐར་སྟོད་ཆ།
  languages:
  - bo
  author: ཞབས་དཀར་བ་ཚོགས་དྲུག་རང་གྲོལ།
statistics:
  ocr_word_mean_confidence_index: 0.961004520689243
  ocr_word_median_confidence_index: 0.99592704
bases:
  I1740:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1740
      total_pages: 470
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1740.txt
    statistics:
      ocr_word_median_confidence_index: 0.99592704
      ocr_word_mean_confidence_index: 0.961004520689243
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
